# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='already_processed',
            field=models.BooleanField(default=False),
        ),
    ]
