# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='remaining_units',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_units',
            field=models.PositiveIntegerField(),
        ),
    ]
